  [build]
  command = "npm run build"
  publish = "dist"


  [[plugins]]
    package = "@netlify/plugin-nextjs" # optional, if you're using Next.js

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
